sudo: false

language: node_js

node_js:
- node

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8-multilib
    - g++-4.8-multilib
    - gcc-multilib
    - g++-multilib

os:
- linux
- osx
- windows
